name: Publish a new version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: True
        description: 'major, minor, patch'
        # Remove the default when done developing
        default: 'patch'
      npm_tag:
        required: True
        description: 'Use "dev" if this is not supposed to be the "latest" version that gets pulled by everyone'
        default: 'latest'
      pre_release:
        type: boolean
        description: 'This is a pre release.'
        required: false
        default: false
      tmate:
        type: boolean
        description: 'Run the build with tmate enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
      #comment:
      #  required: True
      #  description: 'The entry for the changelog'
      #  # Remove default once this is ready
      #  default: 'Update'
      #version:
      #  required: True
      #  description: 'Number representing the version to release'
      #  default: '4.9.2'

jobs:

  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    # First step, manually, before all this - update our changelog?
    name: Release new version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Dry run to get new version
      - name: Get new version
        id: bump
        # https://github.com/MeilCli/bump-release-action
        uses: MeilCli/bump-release-action@v1
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump_type }}
          dry_run: true
          pre_release: ${{ github.event.inputs.pre_release }}
          #draft: false
      - name: Echo outputs
        run: |
          echo ${{ steps.bump.outputs.current_version }}
          echo ${{ steps.bump.outputs.next_version }}
          echo ${{ steps.bump.outputs.release }}

      # Find and replace the ALKiln version in the developer's folder
      # in package.json and install package-lock.json. In our action.yml
      # we'll need to use `npm ci` instead of `npm install`
      - name: Update users' package-lock.json
        run: |
          cd user_files
          # In our folder user_files, this will create the necessary version
          # of ALKiln that we will later copy for our users, as well as the
          # whole package-lock.json
          npm install --save-exact @suffolklitlab/alkiln@${{ steps.bump.outputs.next_version }}
          # Get back to the root folder again to do other release stuff
          cd ..
        shell: bash

      #- name: Set up tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tmate }}

      # Set our package version, push with GitHub tag release
      - name: Bump, publish, and release gh tag
        uses: MeilCli/bump-release-action@v1
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump_type }}
          dry_run: false
          # Temp
          draft: true
          pre_release: ${{ github.event.inputs.pre_release }}

      # Publish on npm
      - name: Publish
        run: npm publish --tag ${{ github.event.inputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
        shell: bash

